/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package co.edu.unicauca.openmarket.presentation;

import co.edu.unicauca.openmarket.domain.Category;
import co.edu.unicauca.openmarket.domain.service.CategoryService;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author william - alejandros
 */
public class GUICategoriesFind extends javax.swing.JDialog {
    private CategoryService categoryService;
    /**
     * Creates new form GUICategoriesFind
     */
    public GUICategoriesFind(java.awt.Frame parent, boolean modal, CategoryService categoryService) {
        super(parent, modal);
        initComponents();
        initializeTable();
        this.categoryService = categoryService;
        setLocationRelativeTo(null);
        
    }
    
    private void initializeTable() {
        tblCategories.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Id", "Name"
                }
        ));
    }
    
    private void fillTableAllCategories(List<Category> listCategories) {
        initializeTable();
        DefaultTableModel modelC = (DefaultTableModel) tblCategories.getModel();

        Object rowData[] = new Object[3];//No columnas
        for (int i = 0; i < listCategories.size(); i++) {
            rowData[0] = listCategories.get(i).getCategoryId();
            rowData[1] = listCategories.get(i).getName();
            
            modelC.addRow(rowData);
        }
    }
    
    private void fillTableOneCategorie(Category objCategory){
        initializeTable();
        DefaultTableModel modelC = (DefaultTableModel) tblCategories.getModel();

        Object rowData[] = new Object[3];//No columnas
        
        rowData[0] = objCategory.getCategoryId();
        rowData[1] = objCategory.getName();
        
        modelC.addRow(rowData);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngBusquedaporC = new javax.swing.ButtonGroup();
        pnlCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategories = new javax.swing.JTable();
        pnlSouth = new javax.swing.JPanel();
        btnCerrarC = new javax.swing.JButton();
        pnlNorth = new javax.swing.JPanel();
        lblBuscarC = new javax.swing.JLabel();
        rdIdC = new javax.swing.JRadioButton();
        rdNombreC = new javax.swing.JRadioButton();
        txtBusquedaC = new javax.swing.JTextField();
        btnBuscarC = new javax.swing.JButton();
        btnBuscarTodoC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda de Categorías");
        setMinimumSize(new java.awt.Dimension(567, 84));
        setPreferredSize(new java.awt.Dimension(700, 478));

        pnlCenter.setLayout(new java.awt.BorderLayout());

        tblCategories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCategories);

        pnlCenter.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        btnCerrarC.setText("Cerrar");
        btnCerrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarCActionPerformed(evt);
            }
        });
        pnlSouth.add(btnCerrarC);

        getContentPane().add(pnlSouth, java.awt.BorderLayout.PAGE_END);

        pnlNorth.setMinimumSize(new java.awt.Dimension(567, 34));
        pnlNorth.setPreferredSize(new java.awt.Dimension(565, 42));

        lblBuscarC.setText("Buscar por:");
        pnlNorth.add(lblBuscarC);

        btngBusquedaporC.add(rdIdC);
        rdIdC.setSelected(true);
        rdIdC.setText("Id");
        pnlNorth.add(rdIdC);

        btngBusquedaporC.add(rdNombreC);
        rdNombreC.setText("Nombre de la categoría");
        rdNombreC.setMaximumSize(new java.awt.Dimension(159, 22));
        rdNombreC.setMinimumSize(new java.awt.Dimension(159, 22));
        pnlNorth.add(rdNombreC);

        txtBusquedaC.setPreferredSize(new java.awt.Dimension(62, 32));
        pnlNorth.add(txtBusquedaC);

        btnBuscarC.setText("Buscar");
        btnBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCActionPerformed(evt);
            }
        });
        pnlNorth.add(btnBuscarC);

        btnBuscarTodoC.setText("Buscar Todos");
        btnBuscarTodoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTodoCActionPerformed(evt);
            }
        });
        pnlNorth.add(btnBuscarTodoC);

        getContentPane().add(pnlNorth, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarCActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarCActionPerformed

    private void btnBuscarTodoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTodoCActionPerformed
        // TODO add your handling code here:
        fillTableAllCategories(categoryService.findAllCategories());
    }//GEN-LAST:event_btnBuscarTodoCActionPerformed

    private void btnBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCActionPerformed
        // TODO add your handling code here:
        if(this.rdIdC.isSelected()== true){
            fillTableOneCategorie(categoryService.findCategoryById(Long.parseLong(this.txtBusquedaC.getText())));
        }
        else if(this.rdNombreC.isSelected()==true){
            fillTableOneCategorie(categoryService.findCategoryByName(this.txtBusquedaC.getText()));
        }
        else{
            System.out.println("ERROR!");
        }
    }//GEN-LAST:event_btnBuscarCActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarC;
    private javax.swing.JButton btnBuscarTodoC;
    private javax.swing.JButton btnCerrarC;
    private javax.swing.ButtonGroup btngBusquedaporC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarC;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlNorth;
    private javax.swing.JPanel pnlSouth;
    private javax.swing.JRadioButton rdIdC;
    private javax.swing.JRadioButton rdNombreC;
    private javax.swing.JTable tblCategories;
    private javax.swing.JTextField txtBusquedaC;
    // End of variables declaration//GEN-END:variables
}
